import { defineConfig } from 'vitest/config';
import tsconfigPaths from 'vite-tsconfig-paths';

export default defineConfig({
    plugins: [tsconfigPaths()],
    test: {
        environment: 'node',
        setupFiles: ['./vitest.setup.ts'],
        coverage: {
            provider: 'v8',
            reporter: ['text', 'html'],
            include: [
                'src/lib/utils.ts',
                'src/lib/env.ts',
                'src/lib/midtrans.ts',
                'src/lib/sounds.ts',
                'src/lib/supabase/client.ts',
                'src/lib/supabase/server.ts',
                'src/lib/i18n/store.ts',
                'src/lib/i18n/useTranslation.ts',
                'src/components/error-boundary.tsx',
                'src/components/theme-provider.tsx',
                'src/components/theme-toggle.tsx',
                'src/components/language-switcher.tsx',
                'src/components/exam/exam-interface.tsx',
                'src/components/quiz-game/quiz-game.tsx',
                'src/components/layout/dashboard-layout.tsx',
                'src/components/layout/sidebar.tsx',
                'src/components/ui/index.tsx',
                'src/components/ui/announcement-banner.tsx',
                'src/stores/auth-store.ts',
                'src/stores/exam-store.ts',
                'src/stores/quiz-game-store.ts',
                'src/proxy.ts',
                'src/app/page.tsx',
                'src/app/layout.tsx',
                'src/app/landing-client.tsx',
                'src/app/dashboard/layout.tsx',
                'src/app/dashboard/page.tsx',
                'src/app/dashboard/emod/page.tsx',
                'src/app/dashboard/latsol/page.tsx',
                'src/app/dashboard/live/page.tsx',
                'src/app/dashboard/vod/page.tsx',
                'src/app/dashboard/tryout/page.tsx',
                'src/app/dashboard/leaderboard/page.tsx',
                'src/app/dashboard/payment-required/page.tsx',
                'src/app/dashboard/scores/page.tsx',
                'src/app/dashboard/payment/page.tsx',
                'src/app/dashboard/strengthens/page.tsx',
                'src/app/dashboard/tutor/page.tsx',
                'src/app/dashboard/tutor/attendance/page.tsx',
                'src/app/dashboard/tutor/scores/page.tsx',
                'src/app/auth/callback/route.ts',
                'src/app/auth/login/page.tsx',
                'src/app/auth/register/page.tsx',
                'src/app/auth/staff-login/page.tsx',
                'src/app/api/attendance/route.ts',
                'src/app/api/admin/classes/route.ts',
                'src/app/api/admin/users/route.ts',
                'src/app/api/auth/seed-admin/route.ts',
                'src/app/api/questions/route.ts',
                'src/app/api/submit-exam/route.ts',
                'src/app/api/payment/status/route.ts',
                'src/app/api/payment/route.ts',
                'src/app/api/payment/create-qris/route.ts',
                'src/app/api/payment/webhook/route.ts',
            ],
            thresholds: {
                statements: 100,
                branches: 100,
                functions: 100,
                lines: 100,
            },
        } as any,
    },
});
